[package]
name = "audio-visualizer"
description = """
Audio visualization library for developers: quickly check audio samples
visually, e.g. while working on audio algorithms.
"""
version = "0.6.0"
authors = ["Philipp Schuster <phip1611@gmail.com>"]
edition = "2024"
rust-version = "1.88.0"
keywords = ["audio", "visualizer", "waveform", "spectrum"]
categories = ["multimedia::audio", "development-tools"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/phip1611/audio-visualizer"
repository = "https://github.com/phip1611/audio-visualizer"
documentation = "https://docs.rs/audio-visualizer/"
exclude = [
    "res",
    "test"
]

[dependencies]
charts-rs = { version = "1.0", features = ["png"] }
# faster compilation: remove unnecessary features
plotters = { version = "0.3", features = ["bitmap_backend", "line_series"] }
plotters-bitmap = "0.3"
ringbuffer = "0.16"
cpal = "0.18"
minifb = "0.28" # gui window

[dev-dependencies]
lowpass-filter = "0.5"
spectrum-analyzer = "1.9"
symphonia = { version = "0.6", default-features = false, features = ["mp3"] }

# otherwise FFT and other code is too slow
[profile.dev]
opt-level = 1
