[package]
name = "audio-visualizer"
description = "Simple audio visualization library which is especially useful for developers to visually check audio algorithms against the waveform."
version = "0.1.4"
authors = ["Philipp Schuster <phip1611@gmail.com>"]
edition = "2018"
keywords = ["audio", "visualizer", "waveform"]
categories = ["multimedia::audio", "development-tools"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/phip1611/audio-visualizer"
repository = "https://github.com/phip1611/audio-visualizer"
documentation = "https://docs.rs/audio-visualizer/"

[dependencies]
png = "0.16.8"
minimp3 = "0.5.1"
