[package]
name = "audio-visualizer"
description = """
Super basic and simple audio visualization library which is especially useful for developers to visually check audio
samples, e.g. by waveform or spectrum. (So far) this library is not capable of doing nice visualizations
for end users.
"""
version = "0.2.4"
authors = ["Philipp Schuster <phip1611@gmail.com>"]
edition = "2018"
keywords = ["audio", "visualizer", "waveform", "spectrum"]
categories = ["multimedia::audio", "development-tools"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/phip1611/audio-visualizer"
repository = "https://github.com/phip1611/audio-visualizer"
documentation = "https://docs.rs/audio-visualizer/"

[dependencies]
png = "0.17.1"
minimp3 = "0.5.1"
plotters = "0.3.1"

# otherwise FFT and other code is too slow
[profile.dev]
opt-level = 1
